import { Inter } from "next/font/google";
import NextAuthProvider from "@/providers/NextAuthProvider";
import TopMenu from '../components/TopMenu';
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <header>
            <TopMenu />
          </header>
          <main className="container mx-auto mt-8">
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}